- name: Define required variables for configuration
  set_fact:
    daemon_location: "{{ install_target_dir }}/cloudflared"
    systemd_filename: "cloudflared"
- name: Install cloudflared service for service '{{ tunnel_name }}''
  template:
    src: cloudflared.service.j2
    dest: "{{ systemd_target_dir }}/{{ systemd_filename }}@.service"
  register: service_template
- name: Reload systemd
  systemd:
    daemon_reload: yes
    no_block: no
  when: service_template.changed
