- name: Find current tunnel config files
  find:
    paths: "{{ config_dir_tunnels }}"
    patterns: '*.yml'
  register: tunnel_configs
- name: Remove unmanaged tunnels
  include_tasks: remove-tunnel.yml
  loop: "{{ tunnel_configs.files | map(attribute='path') | map('basename') | map('splitext') | map('first') }}"
  when: remove_unmanaged_tunnels and (item not in tunnels)
- name: Create config file for service '{{ item.key }}'
  template:
    src: config.yml.j2
    dest: "{{ config_dir_tunnels }}/{{ item.key }}.yml"
  with_dict: "{{ tunnels }}"
- name: Start systemd service {{ item.key }}
  systemd:
    name: "{{ systemd_filename }}@{{ item.key }}"
    state: started
    enabled: yes
    daemon_reload: yes
    no_block: no
  with_dict: "{{ tunnels }}"
